name: CI/CD Pipeline para Lambda

on:
  push:
    branches: [pc-windows]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        working-directory: python/03_lambda_auto_deploy
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests
        working-directory: python/03_lambda_auto_deploy
        run: pytest

      - name: Empaquetar código en ZIP
        working-directory: python/03_lambda_auto_deploy
        run: zip function.zip main.py requirements.txt 
      
      - name: Verificar archivo ZIP
        working-directory: python/03_lambda_auto_deploy
        run: ls -lh function.zip
      
      - name: Configurar AWS CLI
        run: |
          echo "Configurando AWS CLI"
          aws --version
          aws configure set default.region ${{ secrets.AWS_REGION }}
          aws configure set default.output json  

      - name: Probar conexión con Lambda
        working-directory: python/03_lambda_auto_deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws lambda list-functions


      - name: Desplegar en AWS Lambda
        working-directory: python/03_lambda_auto_deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

          aws lambda update-function-code \
            --function-name "$LAMBDA_FUNCTION_NAME" \
            --zip-file fileb://function.zip
